# Generated by Django 3.2.5 on 2021-11-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0002_auto_20211109_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='animate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ani_image/'),
        ),
    ]
