# Generated by Django 3.2.5 on 2021-11-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0003_animate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animateimage',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
