# Generated by Django 3.2.5 on 2021-11-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0004_animateimage_image_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animate',
            name='left_right',
            field=models.CharField(choices=[('L', '좌->우'), ('R', '우->좌')], default='좌', max_length=5),
        ),
    ]
