# Generated by Django 3.2.5 on 2021-11-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0005_alter_animate_left_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='animate',
            name='toon_comic',
            field=models.CharField(choices=[('T', '웹툰 형식'), ('C', '만화책형식')], default='좌', max_length=5),
        ),
        migrations.AddField(
            model_name='animate',
            name='transition_effect',
            field=models.CharField(choices=[('D', '디졸브'), ('U', '위로 슬라이드'), ('Lt', '왼쪽으로 슬라이드'), ('Rt', '오른쪽으로 슬라이드')], default='좌', max_length=5),
        ),
    ]
