# Generated by Django 3.2.5 on 2021-11-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0007_auto_20211116_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='animate',
            name='ani_effect',
            field=models.CharField(choices=[('B', '말풍선'), ('N', '없음')], default='N', max_length=5),
        ),
        migrations.AlterField(
            model_name='animate',
            name='transition_effect',
            field=models.CharField(choices=[('D', '디졸브'), ('U', '위로 슬라이드'), ('Lt', '왼쪽으로 슬라이드'), ('Rt', '오른쪽으로 슬라이드'), ('N', '없음')], default='N', max_length=5),
        ),
    ]
