# Generated by Django 3.2.5 on 2021-11-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0008_auto_20211117_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='animateimage',
            name='ani_effect',
            field=models.CharField(default='N', max_length=5),
        ),
        migrations.AddField(
            model_name='animateimage',
            name='left_right',
            field=models.CharField(default='L', max_length=5),
        ),
        migrations.AddField(
            model_name='animateimage',
            name='toon_comic',
            field=models.CharField(default='T', max_length=5),
        ),
        migrations.AddField(
            model_name='animateimage',
            name='transition_effect',
            field=models.CharField(default='N', max_length=5),
        ),
    ]
